version: "3.8"
services:
  dropbase-server:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile-server
    volumes:
      - ./workspace:/project/workspace
    ports:
      - "9090:9090"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
  dropbase-lsp:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile-lsp
    volumes:
      - ./workspace:/project/workspace
    ports:
      - "9095:9095"
    environment:
      - PYTHONUNBUFFERED=1