FROM golang:1.21 AS building

COPY . /building
WORKDIR /building

RUN cd /building/proxy/frp && make frpc

FROM alpine:3

RUN apk add --no-cache gettext

COPY --from=building /building/proxy/frp/bin/frpc /usr/bin/frpc
COPY --from=building /building/proxy/proxy-config.sh /proxy-config.sh

ENTRYPOINT ["/bin/sh", "/proxy-config.sh"]
