FROM golang:1.21 AS building

COPY . /building
WORKDIR /building

RUN cd /building/proxy/frp && make frpc

FROM alpine:3

RUN apk add --no-cache gettext

COPY --from=building /building/proxy/frp/bin/frpc /usr/bin/frpc
COPY proxy-config.sh /proxy-config.sh

RUN chmod +x /proxy-config.sh

ENTRYPOINT ["/bin/sh", "/proxy-config.sh"]



# FROM golang:1.21 AS building

# COPY . /building
# WORKDIR /building

# RUN make frpc

# FROM alpine:3

# COPY --from=building /building/bin/frpc /usr/bin/frpc

# ENTRYPOINT ["/usr/bin/frpc"]