version: "3.8"
services:
  dropbase-server:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile-server
    volumes:
      - ./workspace:/project/workspace
    ports:
      - "9090:9090"
    env_file:
      - .env
    healthcheck:
      test: curl --fail http://localhost:9090/health/ || exit 1
      interval: 60s
      timeout: 30s
      retries: 1
      start_period: 30s
    environment:
      - PYTHONUNBUFFERED=1
    labels:
      - "autoheal=true"
  dropbase-lsp:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile-lsp
    volumes:
      - ./workspace:/project/workspace
    ports:
      - "9095:9095"
    healthcheck:
      test: curl http://localhost:9095/ || exit 1
      interval: 60s
      timeout: 30s
      retries: 1
      start_period: 30s
    environment:
      - PYTHONUNBUFFERED=1
    labels:
      - "autoheal=true"
  autoheal:
    image: willfarrell/autoheal:latest  # https://github.com/willfarrell/docker-autoheal
    tty: true
    restart: always
    environment:
      - AUTOHEAL_INTERVAL=60
      - AUTOHEAL_START_PERIOD=30
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
