FROM python:3.11-slim-buster

# Install basic packages
RUN apt-get update -y && apt-get install libffi-dev libmagic1 git libpq-dev -y \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /project

# Install python libraries
COPY requirements.txt requirements.txt

RUN pip3 install --no-cache-dir --upgrade -r requirements.txt

# install dropbase package
ADD dropbase/. dropbase/.
RUN pip install dropbase/.

ADD server/. server/.

EXPOSE 9090

CMD uvicorn server.main:app --reload --host 0.0.0.0 --port 9090
