# Use an official Python runtime as a parent image
FROM python:3.11-slim

# RUN apt-get update && apt-get install -y ssh

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD worker/. .
ADD dropbase/. dropbase/.
RUN pip install -e dropbase/.

# Install packages
ADD requirements-worker.txt requirements-worker.txt
RUN pip install -r requirements-worker.txt
RUN pip install -r requirements-custom.txt