version: "3.8"
services:
  dropbase-server:
    build:
      context: .
      dockerfile: Dockerfile-server
    volumes:
      - ./workspace:/project/workspace
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
  dropbase-lsp:
    build:
      context: .
      dockerfile: Dockerfile-lsp
    volumes:
      - ./workspace:/project/workspace
    ports:
      - "9001:9001"
    environment:
      - PYTHONUNBUFFERED=1
  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    environment:
      - FRPS_SERVER_PORT
      - DROPBASE_WORKER_PORT
      - DROPBASE_LSP_PORT
      - DROPBASE_PROXY_SERVER_URL
      - DROPBASE_PROXY_SERVER_TOKEN