FROM python:3.11-slim-buster

# Install basic packages
RUN apt-get update -y && apt-get install libffi-dev libmagic1 git libpq-dev -y \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /project

# Install default Python libraries
COPY requirements.txt requirements.txt
RUN pip3 install --no-cache-dir --upgrade -r requirements.txt

# Install dropbase package
# ADD dropbase/. dropbase/.
# RUN pip install dropbase/.

ADD server/. server/.

EXPOSE 9090

# Make our startup script executable
RUN mkdir .temp

# Copy the startup script into known file location in container
COPY start.sh /start.sh

# Make our startup script executable
RUN chmod +x /start.sh

CMD ["/start.sh"]