#!/bin/bash

if [[ $1 == 's' ]]; then
    # docker build -f Dockerfile-worker -t worker .
    # pip install -U -e dropbase/.
    uvicorn server.main:app --reload --reload-dir server/ --host 0.0.0.0 --port 9090
elif [[ $1 == 'l' ]]; then
    pylsp --ws --port 9095
else
    echo "Invalid argument, please use 's' for server and 'l' for lsp."
fi

# unset DROPBASE_TOKEN DROPBASE_API_URL STRIPE_KEY AWS_ACCESS_KEY AWS_SECRET_KEY HOST_WORKSPACE_PATH \
# TASK_TIMEOUT PEOPLEDATALABS_KEY pypy_username pypi_token \
# SOURCE_PG_WEBINAR_HOST SOURCE_PG_WEBINAR_DATABASE SOURCE_PG_WEBINAR_USERNAME SOURCE_PG_WEBINAR_PASSWORD SOURCE_PG_WEBINAR_PORT SOURCE_PG_REPLICA_HOST SOURCE_PG_REPLICA_DATABASE SOURCE_PG_REPLICA_USERNAME SOURCE_PG_REPLICA_PASSWORD SOURCE_PG_REPLICA_PORT SOURCE_PG_PARAM_HOST SOURCE_PG_PARAM_DATABASE SOURCE_PG_PARAM_USERNAME SOURCE_PG_PARAM_PASSWORD SOURCE_PG_PARAM_PORT SOURCE_PG_ALICIA_HOST SOURCE_PG_ALICIA_DATABASE SOURCE_PG_ALICIA_USERNAME SOURCE_PG_ALICIA_PASSWORD SOURCE_PG_ALICIA_PORT SOURCE_PG_JIMMY_HOST SOURCE_PG_JIMMY_DATABASE SOURCE_PG_JIMMY_USERNAME SOURCE_PG_JIMMY_PASSWORD SOURCE_PG_JIMMY_PORT SOURCE_PG_LOCAL_HOST SOURCE_PG_LOCAL_DATABASE SOURCE_PG_LOCAL_USERNAME SOURCE_PG_LOCAL_PASSWORD SOURCE_PG_LOCAL_PORT SOURCE_PG_DROP_HOST SOURCE_PG_DROP_DATABASE SOURCE_PG_DROP_USERNAME SOURCE_PG_DROP_PASSWORD SOURCE_PG_DROP_PORT GITHUT_PERSONAL_TOKEN