from server.controllers.tables.gpt_templates.mysql_gpt_template import get_mysql_gpt_input
from server.controllers.tables.gpt_templates.postgres_gpt_template import get_postgres_gpt_input
from server.controllers.tables.gpt_templates.snowflake_gpt_template import get_snowflake_gpt_input
from server.controllers.tables.gpt_templates.sqlite_gpt_template import get_sqlite_gpt_input
